name: sapa
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  go_router: ^14.2.1
  appwrite: ^12.0.0
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.6
  intl: ^0.20.2
  image_picker: ^1.1.2
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.0
  fl_chart: ^1.0.0
  pdf: ^3.11.3
  printing: ^5.14.2
  flutter_launcher_icons: ^0.14.4
  double_tap_to_exit: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  json_serializable: ^6.8.0
  freezed: ^2.5.2

dependency_overrides:
  flutter_web_auth_2: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo_sapa.png"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/.env
